//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HNetPortal.Private {
    
    
    public partial class Calendar {
        
        /// <summary>
        /// CalEditDialog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HNetPortal.Controls.CalEditDialog CalEditDialog;
        
        /// <summary>
        /// CalSearchDialog control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HNetPortal.Controls.CalSearchDialog CalSearchDialog;
    }
}
